In [77]:
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b[1,1] = 10
print(a.shape)
print(b.shape)
print(b)

(3,)
(3, 3)
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]


In [6]:
persontype = np.dtype({
    'names':['name','age','chinese','math','english'],
    'formats':['S32','i','i','i','f']
})
peoples = np.array([
    ('ZhangFen',32,75,100,90),
    ('GuanYu',24,85,96,88.5),
    ('ZhaoYun',28,85,92,96.5),
    ('HuangZhong',29,65,85,100)
], dtype = persontype)
ages = peoples[:]['age']
chineses = peoples[:]['chinese']
maths = peoples[:]['math']
englishs = peoples[:]['english']

print(np.mean(ages))
print(np.mean(chineses))
print(np.mean(maths))
print(np.mean(englishs))

print(ages)

28.25
77.5
93.25
93.75
[32 24 28 29]


In [36]:
x1 = np.arange(1,11,2)
x2 = np.linspace(1,9,5)
x3 = np.array([2,2,2,2,2])

print(x1, x2)
print(np.add(x1, x2), x1 + x2)
print(np.subtract(x1, x2), x1 - x2)
print(np.multiply(x1, x2), x1 * x2)
print(np.divide(x1, x2), x1 / x2)
print(np.power(x1, x2))
print(np.power(x1, x3))
print(np.remainder(x1, x2), np.mod(x1, x2))

[1 3 5 7 9] [1. 3. 5. 7. 9.]
[ 2.  6. 10. 14. 18.] [ 2.  6. 10. 14. 18.]
[0. 0. 0. 0. 0.] [0. 0. 0. 0. 0.]
[ 1.  9. 25. 49. 81.] [ 1.  9. 25. 49. 81.]
[1. 1. 1. 1. 1.] [1. 1. 1. 1. 1.]
[1.00000000e+00 2.70000000e+01 3.12500000e+03 8.23543000e+05
 3.87420489e+08]
[ 1  9 25 49 81]
[0. 0. 0. 0. 0.] [0. 0. 0. 0. 0.]


In [54]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)
print(np.ndim(a))
print(a)
print(np.amin(a))
print(np.amin(a,0))
print(np.amin(a,1))
print(np.ptp(a))
print(np.ptp(a,0))
print(np.ptp(a,1))

(3, 3)
2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
[1 2 3]
[1 4 7]
8
[6 6 6]
[2 2 2]


In [51]:
three = np.array([
    [
        [1,2],[3,4]
    ],
    [
        [5,6],[7,8]
    ]
])
print(three.shape)
print(np.ndim(three))
print(np.amin(three))
print('')
print(np.amin(three,0))
print('')
print(np.amin(three,1))
print('')
print(np.amin(three,2))
print(np.amin(three,2).shape)
print('====')
print(three)

(2, 2, 2)
3
1

[[1 2]
 [3 4]]

[[1 2]
 [5 6]]

[[1 3]
 [5 7]]
(2, 2)
====
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [76]:
aa = np.array([[4,3,2], [2,4,1]])
print(np.sort(aa, axis = 1))

[[2 3 4]
 [1 2 4]]


In [80]:
a = np.array([
    [1,0],
    [0,1]
])
b = np.array([
    [4],
    [2]
])

print(a.shape, b.shape)
np.matmul(a, b)

(2, 2) (2, 1)


array([[4],
       [2]])